name: Refresh traffic data

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/traffic.yml'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: echo "minimal traffic - testing trigger"
